version: '3'
services:
  api:
    container_name: api
    build: api
    links:
      - mongodb
    ports:
      - 8080:8080
    environment:
      - PORT=8080
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
  web:
    container_name: web
    build: web
    ports:
      - 3000:3000

